# -*- coding: utf-8 -*-
"""is_Serrated.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zURq6RS3QpT4qCRkf-_vncrJdaROMn19
"""

import random

def is_serrated(sequence):
    sign = 1 
    for i in range(1, len(sequence)):
        if sequence[i] == sequence[i-1]:
            return False
        if (sequence[i] - sequence[i-1]) * sign < 0: 
            return False
        sign = -sign
    return True


if __name__ == '__main__':
  trials = 10**6
  serrated_count = 0
  my_list = [1,2,3,4,5,6]
  for _ in range(trials):
      sequence = [random.choice(my_list) for _ in range(5)]
      if is_serrated(sequence):
          serrated_count += 1

  probability = serrated_count/trials
  print(probability)