# -*- coding: utf-8 -*-
"""running_fraction_of_two's.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVPnkK_INsl1w_TGMS6-qNFOV-H7wwV4
"""

import random
import matplotlib.pyplot as plt

def plot_running_fraction_of_twos():
    rolls = [random.randint(1, 6) for _ in range(1000)]
    running_fraction_of_twos = [0]
    two_count = 0
    for i in range(1, len(rolls) + 1):
        if rolls[i-1] == 2:
            two_count += 1
        running_fraction_of_twos.append(two_count/i)
    
    
    plt.plot(running_fraction_of_twos)
    plt.xlabel("rolls")
    plt.ylabel("Running frac")
    plt.show()

plot_running_fraction_of_twos()

